#!/usr/bin/env bash
clear
normal=`echo -en "\e[0m"`
bold=`echo -en "\e[1m"`
green=`echo -en "\e[32m"`
orange=`echo -en "\e[33m"`
clipfile="/tmp/tmpclp.txt"
if [[ -f "$clipfile" ]]
then
    clpman="$(bat $clipfile | uniq | fzf --prompt="Copy : " --border --margin=5% --color=dark --height=100% --reverse --header-first --header=" CLIPXF ")"
    if [[ "$clpman" ]];
    then
        echo -e "$clpman" | /usr/bin/xclip -sel c
    else
        exit 0
    fi
else
    touch "$clipfile" && chmod 600 "$clipfile" && echo -e "$clpman" | /usr/bin/xclip -sel c && printf "${green}No ${bold}${orange}Clipman${normal}${green}, empty ${bold}%s${normal}${green} created!\n" "$clipfile"
    exit 0
fi
exit 0

