#!/usr/bin/env bash
set -eo pipefail

batcheck="$("$HOME"/scripts/battery)"
dte="$(/usr/bin/date +"%a %b %e %r")"
syscheck="$(printf "%s\t\t%s\n" "$dte" "$batcheck")"
/usr/bin/notify-send -t 4000 "$syscheck" && printf "%s\n" "$syscheck"
exit
