#!/usr/bin/env bash
set -eo pipefail
normal="\e[0m"
bold="\e[1m"
green="\e[32m"
orange="\e[33m"

clipfile="/tmp/tmpclp.txt"

# if clipfile exists copy clipboard into clipfile
if [[ -f "$clipfile" ]]
then
    /usr/bin/echo -e "$(/usr/bin/xclip -sel c -o)" >> "$clipfile"

# if clipfile exists, create it, then copy clipboard into clipfile
else
    /usr/bin/touch "$clipfile" \
		&& /usr/bin/chmod 600 "$clipfile" \
		&& /usr/bin/echo -e "$(/usr/bin/xclip -sel c -o)" >> "$clipfile" \
		&& printf "${green}No ${bold}${orange}Clipman${normal}${green}, empty ${bold}%s${normal}${green} created!\n" "$clipfile"
fi
exit 0

