#!/usr/bin/env bash
set -eo pipefail

#echo -e "$(/usr/bin/xclip -sel c -o)" >> /tmp/tmpclp.txt
clipfile="/tmp/tmpclp.txt"
if [[ -f "$clipfile" ]]
then
    /usr/bin/xclip -sel c -o >> "$clipfile"
else
    touch "$clipfile" && chmod 600 "$clipfile" && /usr/bin/xclip -sel c -o >> "$clipfile" && printf "${green}No ${bold}${orange}Clipman${normal}${green}, empty ${bold}%s${normal}${green} created!\n" "$clipfile"
    exit 0
fi
exit 0

