#!/usr/bin/env bash
# weekly commonly

/usr/bin/sudo /usr/bin/apt update -y && /usr/bin/sudo /usr/bin/apt upgrade -y && /usr/bin/sudo /usr/bin/apt full-upgrade -y && /usr/bin/sudo /usr/bin/apt-get autoremove --purge -y && /usr/bin/sudo /usr/bin/apt clean -y

## allow-downgrades
#/usr/bin/sudo /usr/bin/apt update -y && /usr/bin/sudo /usr/bin/apt upgrade -y --allow-downgrades && /usr/bin/sudo /usr/bin/apt full-upgrade -y --allow-downgrades && /usr/bin/sudo /usr/bin/apt-get autoremove --purge -y && /usr/bin/sudo /usr/bin/apt clean -y
